In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import plotly.express as px
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
np.set_printoptions(precision=4)
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
import statsmodels.api as sms
presnapoffense = ['pff_QTR','pff_DOWN','pff_OFFFORMUNBAL','pff_RUNPASSOPT', 'pff_WEEK', 'pff_SCREEN', 'pff_DISTANCE',
                  'isshotgun','isemptybackfield','teleft','teright','teboth','numberwidereceivers','numberrunningbacks','numbertightends','numberwrleft',
                 'numberwrright','numberpassblocking','blitz']

# This part makes it so that you only look at the pass plays
TCUdata = pd.read_csv('TCUTrainExosClean.csv') # Type the historic data file name into the blank
TCUdata = TCUdata.loc[:,presnapoffense]

TCUtestdata = pd.read_csv('TCUTestExosClean.csv') # Type the test data file name into the blank
TCUtestdata = TCUtestdata.loc[:,presnapoffense]

# Creates the model
X_train, X_test = TCUdata.drop('blitz', axis=1), TCUtestdata.drop('blitz', axis=1)
y_train, y_test = TCUdata['blitz'], TCUtestdata['blitz']
logmodel = LogisticRegression()
logmodel.fit(X_train, y_train)
y_pred = logmodel.predict(X_test)
print('For TCU:')
print('')
print(classification_report(y_test, y_pred))

# Prints confusion matrix
print('------------------------------------------------------')
print('How to read the confusion matrix:')
print('')
cfdef = [['Correctly predicted non-blitz','False positive for blitz'],['False negative for blitz','Correctly predicted blitz']]
print(cfdef[0])
print(cfdef[1])
print('')
print(confusion_matrix(y_test, y_pred))

For TCU:

              precision    recall  f1-score   support

           0       0.55      1.00      0.71        38
           1       0.00      0.00      0.00        31

    accuracy                           0.55        69
   macro avg       0.28      0.50      0.36        69
weighted avg       0.30      0.55      0.39        69

------------------------------------------------------
How to read the confusion matrix:

['Correctly predicted non-blitz', 'False positive for blitz']
['False negative for blitz', 'Correctly predicted blitz']

[[38  0]
 [31  0]]


C:\Users\2tann\anaconda3\envs\misenv\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\2tann\anaconda3\envs\misenv\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\2tann\anaconda3\envs\misenv\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are i

In [2]:
# This part makes it so that you only look at the pass plays
Baylordata = pd.read_csv('BaylorTrainExosClean.csv') # Type the historic data file name into the blank
Baylordata = Baylordata.loc[:,presnapoffense]

Baylortestdata = pd.read_csv('BaylorTestExosClean.csv') # Type the test data file name into the blank
Baylortestdata = Baylortestdata.loc[:,presnapoffense]

# Creates the model
BAYX_train, BAYX_test = Baylordata.drop('blitz', axis=1), Baylortestdata.drop('blitz', axis=1)
BAYy_train, BAYy_test = Baylordata['blitz'], Baylortestdata['blitz']
BAYlogmodel = LogisticRegression()
BAYlogmodel.fit(BAYX_train, BAYy_train)
BAYy_pred = logmodel.predict(BAYX_test)
print('For Baylor:')
print('')
print(classification_report(BAYy_test, BAYy_pred))

# Prints confusion matrix
print('')
print('How to read the confusion matrix:')
print('')
cfdef = [['Correctly predicted non-blitz','False positive for blitz'],['False negative for blitz','Correctly predicted blitz']]
print(cfdef[0])
print(cfdef[1])
print('')
print(confusion_matrix(BAYy_test, BAYy_pred))

For Baylor:

              precision    recall  f1-score   support

           0       0.49      1.00      0.66        25
           1       0.00      0.00      0.00        26

    accuracy                           0.49        51
   macro avg       0.25      0.50      0.33        51
weighted avg       0.24      0.49      0.32        51


How to read the confusion matrix:

['Correctly predicted non-blitz', 'False positive for blitz']
['False negative for blitz', 'Correctly predicted blitz']

[[25  0]
 [26  0]]


C:\Users\2tann\anaconda3\envs\misenv\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\2tann\anaconda3\envs\misenv\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\2tann\anaconda3\envs\misenv\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are i

In [3]:
# This part makes it so that you only look at the pass plays
Kansasdata = pd.read_csv('KansasTrainExosClean.csv') # Type the historic data file name into the blank
Kansasdata = Kansasdata.loc[:,presnapoffense]

Kansastestdata = pd.read_csv('KansasTestExosClean.csv') # Type the test data file name into the blank
Kansastestdata = Kansastestdata.loc[:,presnapoffense]

# Creates the model
KansasX_train, KansasX_test = Kansasdata.drop('blitz', axis=1), Kansastestdata.drop('blitz', axis=1)
Kansasy_train, Kansasy_test = Kansasdata['blitz'], Kansastestdata['blitz']
Kansaslogmodel = LogisticRegression()
Kansaslogmodel.fit(KansasX_train, Kansasy_train)
Kansasy_pred = logmodel.predict(KansasX_test)
print('For Kansas:')
print('')
print(classification_report(Kansasy_test, Kansasy_pred))

# Prints confusion matrix
print('')
print('How to read the confusion matrix:')
print('')
cfdef = [['Correctly predicted non-blitz','False positive for blitz'],['False negative for blitz','Correctly predicted blitz']]
print(cfdef[0])
print(cfdef[1])
print('')
print(confusion_matrix(Kansasy_test, Kansasy_pred))

For Kansas:

              precision    recall  f1-score   support

           0       0.76      0.98      0.86        60
           1       0.00      0.00      0.00        19

    accuracy                           0.75        79
   macro avg       0.38      0.49      0.43        79
weighted avg       0.57      0.75      0.65        79


How to read the confusion matrix:

['Correctly predicted non-blitz', 'False positive for blitz']
['False negative for blitz', 'Correctly predicted blitz']

[[59  1]
 [19  0]]


C:\Users\2tann\anaconda3\envs\misenv\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [4]:
# This part makes it so that you only look at the pass plays
WVUdata = pd.read_csv('WestVirginiaTrainExosClean.csv') # Type the historic data file name into the blank
WVUdata = WVUdata.loc[:,presnapoffense]

WVUtestdata = pd.read_csv('WestVirginiaTestExosClean.csv') # Type the test data file name into the blank
WVUtestdata = WVUtestdata.loc[:,presnapoffense]

# Creates the model
WVUX_train, WVUX_test = WVUdata.drop('blitz', axis=1), WVUtestdata.drop('blitz', axis=1)
WVUy_train, WVUy_test = WVUdata['blitz'], WVUtestdata['blitz']
WVUlogmodel = LogisticRegression()
WVUlogmodel.fit(WVUX_train, WVUy_train)
WVUy_pred = logmodel.predict(WVUX_test)
print('For WVU:')
print('')
print(classification_report(WVUy_test, WVUy_pred))

# Prints confusion matrix
print('')
print('How to read the confusion matrix:')
print('')
cfdef = [['Correctly predicted non-blitz','False positive for blitz'],['False negative for blitz','Correctly predicted blitz']]
print(cfdef[0])
print(cfdef[1])
print('')
print(confusion_matrix(WVUy_test, WVUy_pred))

For WVU:

              precision    recall  f1-score   support

           0       0.40      1.00      0.57        23
           1       0.00      0.00      0.00        35

    accuracy                           0.40        58
   macro avg       0.20      0.50      0.28        58
weighted avg       0.16      0.40      0.23        58


How to read the confusion matrix:

['Correctly predicted non-blitz', 'False positive for blitz']
['False negative for blitz', 'Correctly predicted blitz']

[[23  0]
 [35  0]]


C:\Users\2tann\anaconda3\envs\misenv\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\2tann\anaconda3\envs\misenv\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\2tann\anaconda3\envs\misenv\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are i

In [5]:
# This part makes it so that you only look at the pass plays
TXdata = pd.read_csv('TexasTrainExosClean.csv') # Type the historic data file name into the blank
TXdata = TXdata.loc[:,presnapoffense]

TXtestdata = pd.read_csv('TexasTestExosClean.csv') # Type the test data file name into the blank
TXtestdata = TXtestdata.loc[:,presnapoffense]

# Creates the model
TXX_train, TXX_test = TXdata.drop('blitz', axis=1), TXtestdata.drop('blitz', axis=1)
TXy_train, TXy_test = TXdata['blitz'], TXtestdata['blitz']
TXlogmodel = LogisticRegression()
TXlogmodel.fit(TXX_train, TXy_train)
TXy_pred = logmodel.predict(TXX_test)
print('For TX:')
print('')
print(classification_report(TXy_test, TXy_pred))

# Prints confusion matrix
print('')
print('How to read the confusion matrix:')
print('')
cfdef = [['Correctly predicted non-blitz','False positive for blitz'],['False negative for blitz','Correctly predicted blitz']]
print(cfdef[0])
print(cfdef[1])
print('')
print(confusion_matrix(TXy_test, TXy_pred))

For TX:

              precision    recall  f1-score   support

           0       0.66      1.00      0.79        56
           1       0.00      0.00      0.00        29

    accuracy                           0.66        85
   macro avg       0.33      0.50      0.40        85
weighted avg       0.43      0.66      0.52        85


How to read the confusion matrix:

['Correctly predicted non-blitz', 'False positive for blitz']
['False negative for blitz', 'Correctly predicted blitz']

[[56  0]
 [29  0]]


C:\Users\2tann\anaconda3\envs\misenv\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\2tann\anaconda3\envs\misenv\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\2tann\anaconda3\envs\misenv\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are i